# Generated by Django 4.1.5 on 2023-02-13 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_store_items_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='qty',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='store_items',
            name='stock_quant',
            field=models.IntegerField(),
        ),
    ]
