# Generated by Django 4.1.5 on 2023-03-09 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_cart_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store_items',
            name='sku_num',
            field=models.IntegerField(),
        ),
    ]
